export const EventTypes = {
    FRONT_TYRES_OVERHEATING: 'FRONT_TYRES_OVERHEATING',
    REAR_TYRES_OVERHEATING: 'REAR_TYRES_OVERHEATING',
    LOW_FUEL: 'LOW_FUEL',
    POSITION_GAINED: 'POSITION_GAINED',
    POSITION_LOST: 'POSITION_LOST',
};